### ISSUE TITLE
Upstreaming the validator-with-filters code

### ISSUE THREAD

**Issue by sideshowbarker** [keeganstreet/HTML5-Validator-with-Filters#1]
Hi Keegan,

I work with Henri Sivonen on the validator.nu source. We're interested in integrating your filters code to add as a feature of the upstream validator.nu UI (the code at http://validator.nu/script.js ).

Would that be OK with you? If so, we'd need to get confirmation from you either to license your code under the MIT license, or that it's in the public domain -- and also find out what copyright notice (if any) to add to the header of the http://validator.nu/script.js file.

  --Mike

P.S. You can also reach me by e-mail at mike@w3.org

**Comment by keeganstreet** [comment]
Hey Mike,

That's great! The work I did on this is in the public domain, so there is no need for any copyright notice. Let me know if I can help with the integration.

Cheers,
Keegan

**Comment by sideshowbarker** [comment]
Hi Keegan, Thanks for the reply. I have the integration done at this point -- I just need to get the code reviewed by Henri before we land it. I'l give you a heads-up before we actually push it out to validator.nu and the W3C service.

> Hey Mike,
> 
> That's great! The work I did on this is in the public domain, so there is
> no need for any copyright notice. Let me know if I can help with the
> integration.
> 
> Cheers,
> Keegan

**Comment by sideshowbarker** [comment]
Didn’t realize I had left this open… (Thanks again much—the code for this landed in the checker long ago, in the https://validator.w3.org/nu/ UI.)

**Comment by keeganstreet** [comment]
Thanks @sideshowbarker. I didn't realise it had landed in the https://validator.w3.org/nu/ UI. Just had a look. Looks good!

**Comment by sideshowbarker** [comment]
Glad you’re happy with the result and yeah sorry I had meant to follow up with you about it way back when it first landed.
